# DRONE SWARM AMBUSH CODE
from PatrolPathGen.anotherone import init, 






# TODO FLIP OBSTACLE MAP BEFORE GIVING IT TO THE PATROL CODE
# SWAP 0 AND 1
# - MAKE 0 INTO 2
# - MAKE 1 INTO 0
# - MAKE 2 INTO 1